fix: fix pre-commit params of husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,34 +1,26 @@
 #!/usr/bin/env sh
 . "$(dirname "$0")/_/husky.sh"
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$")
-
-if [[ "$STAGED_FILES" = "" ]]; then
+if [[ $(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$") = "" ]]; then
   exit 0
 fi
 
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|ts|jsx|tsx)$")
 PASS=true
 
 echo "🔄 Validating Javascript:"
 
-for FILE in $STAGED_FILES
-do
-  yarn eslint "$FILE"
+yarn eslint ${STAGED_FILES[*]} "$@"
 
-  if [[ "$?" == 0 ]]; then
-    echo "✅ ESLint Passed: $FILE"
-  else
-    echo "❌ ESLint Failed: $FILE"
+if [ $? -ne 0 ]; then
+    echo "❌ ESLint Failed"
     PASS=false
-  fi
-done
+    exit 1
+fi
 
 echo "🏁 Javascript validation completed!"
 
 if ! $PASS; then
-  echo "❌ COMMIT FAILED: Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again"
-  exit 1
-else
   echo "✅ COMMIT SUCCEEDED"
 fi
 
